image: "moto.math.nat.tu-bs.de/code/sleqp:7.0.1"

stages:
- prepare
- build
- test
- package
- install
- downstream

variables:
  CTEST_OUTPUT_ON_FAILURE: '1'

# run cmake
prepare:
  stage: prepare
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSLEQP_ENABLE_PYTHON=On
  artifacts:
    paths:
      - build
      - bindings/python

# run make
build:
  stage: build
  script:
    - cd build
    - make -j$(nproc)
  artifacts:
    paths:
      - build
      - bindings/python

# run tests
test:
  stage: test
  script:
    - cd build
    - make build_tests
    - make test
  artifacts:
    paths:
      - build
      - bindings/python

package:
  stage: package
  script:
    - cd build
    - make package
  artifacts:
    paths:
      - build/*.deb
      - build/*.bz2

package_wheel:
  stage: package
  script:
    - cd build
    - make python_sleqp_bdist_wheel
  artifacts:
    paths:
      - bindings/python/dist/*.whl

package_sdist:
  stage: package
  script:
    - cd build
    - make python_sleqp_sdist
  artifacts:
    paths:
      - bindings/python/dist/*.tar.gz

install_package:
  stage: install
  script:
    - cd build
    - apt -y install ./*.deb

# install_wheel:
#   stage: install
#   script:
#     - cd bindings/python/dist/*.whl

trigger_downstream:
  stage: downstream
  only:
    - master
  script:
    - "curl --fail -X POST -F token=${SLEQP_INDO_TRIGGER_TOKEN} ${CI_API_V4_URL}/projects/176/ref/master/trigger/pipeline"
