image: "chrh/sleqp_builddeps:v8"

stages:
- prepare
- build
- test

variables:
  CTEST_OUTPUT_ON_FAILURE: '1'

cache:
  key: "PIPELINE-$CI_PIPELINE_ID"
  paths:
    - build
    - bindings/python

# run cmake
prepare:
  stage: prepare
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DSLEQP_ENABLE_PYTHON=On

# run make
build:
  stage: build
  script:
    - cd build
    - make -j$(nproc)

# run tests
test:
  stage: test
  script:
    - cd build
    - make build_tests
    - make test
