image: "moto.math.nat.tu-bs.de:5050/code/images/sleqp_builddeps:latest"

stages:
  - test
  - build
  - package
  - postpackage
  - deploy
  - release
  - downstream

include:
  - local: /.gitlab/ci/variables.gitlab-ci.yml
  - local: /.gitlab/ci/template.gitlab-ci.yml
  - local: /.gitlab/ci/rules.gitlab-ci.yml
  - local: /.gitlab/ci/test.gitlab-ci.yml
  - local: /.gitlab/ci/build.gitlab-ci.yml
  - local: /.gitlab/ci/package.gitlab-ci.yml
  - local: /.gitlab/ci/postpackage.gitlab-ci.yml
  - local: /.gitlab/ci/deploy.gitlab-ci.yml
  - local: /.gitlab/ci/release.gitlab-ci.yml
  - local: /.gitlab/ci/downstream.gitlab-ci.yml
