image: "moto.math.nat.tu-bs.de:5050/code/images/sleqp_builddeps:latest"

stages:
  - test
  - build
  - package
  - install
  - downstream

variables:
  CTEST_OUTPUT_ON_FAILURE: '1'

# run tests
.test_template: &test_job
  stage: test
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DSLEQP_ENABLE_PYTHON=On
    - make
    - make build_tests
    - PYTHONMALLOC='malloc' make test
  dependencies: []

test_undefined_sanitizer:
  <<: *test_job
  variables:
    CFLAGS: '-g -fsanitize=undefined'

# Not possible due to old compiler
# test_address_sanitizer:
#   <<: *test_job
#   variables:
#     CFLAGS: '-g -fsanitize=address -fno-omit-frame-pointer'

# test_leak_sanitizer:
#   <<: *test_job
#   variables:
#     CFLAGS: '-g -fsanitize=leak'

# test_memory_sanitizer:
#   <<: *test_job
#   variables:
#     CFLAGS: '-g -fsanitize=memory'

build:
  stage: build
  only:
    - master
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_CXX_FLAGS="-O3 -g" -DCMAKE_C_FLAGS="-O3 -g" -DSLEQP_ENABLE_UNIT_TESTS=Off -DSLEQP_ENABLE_PYTHON=On
    - make -j$(nproc)
  artifacts:
    paths:
      - build
      - bindings/python

package:
  stage: package
  only:
    - master
  dependencies:
    - build
  script:
    - cd build
    - make package
  dependencies:
    - build
  artifacts:
    paths:
      - build/*.deb
      - build/*.bz2

package_wheel:
  stage: package
  only:
    - master
  dependencies:
    - build
  script:
    - cd build
    - make python_sleqp_bdist_wheel
  dependencies:
    - build
  artifacts:
    paths:
      - bindings/python/dist/*.whl

package_sdist:
  stage: package
  only:
    - master
  dependencies:
    - build
  script:
    - cd build
    - make python_sleqp_sdist
  dependencies:
    - build
  artifacts:
    paths:
      - bindings/python/dist/*.tar.gz

install_package:
  stage: install
  only:
    - master
  script:
    - cd build
    - apt -y install ./*.deb

trigger_downstream:
  stage: downstream
  only:
    - master
  script:
    - "curl --fail -X POST -F token=${SLEQP_INDO_TRIGGER_TOKEN} ${CI_API_V4_URL}/projects/176/ref/master/trigger/pipeline"
