image: "chrh/sleqp_builddeps:v10"

stages:
- prepare
- build
- test
- package

variables:
  CTEST_OUTPUT_ON_FAILURE: '1'

# run cmake
prepare:
  stage: prepare
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DSLEQP_ENABLE_PYTHON=On
  artifacts:
    paths:
      - build
      - bindings/python

# run make
build:
  stage: build
  script:
    - cd build
    - make -j$(nproc)
  artifacts:
    paths:
      - build
      - bindings/python

# run tests
test:
  stage: test
  script:
    - cd build
    - make build_tests
    - make test
  artifacts:
    paths:
      - build
      - bindings/python

package:
  stage: package
  script:
    - cd build
    - make package
  artifacts:
    paths:
      - build/*.deb
      - build/*.bz2
