package:
  stage: package
  only:
    - master
  dependencies:
    - build
  script:
    - cd build
    - make package
  dependencies:
    - build
  artifacts:
    paths:
      - build/*.deb
      - build/*.bz2

package_wheel:
  stage: package
  only:
    - master
  dependencies:
    - build
  script:
    - cd build
    - make python_sleqp_bdist_wheel
  dependencies:
    - build
  artifacts:
    paths:
      - bindings/python/dist/*.whl

package_sdist:
  stage: package
  only:
    - master
  dependencies:
    - build
  script:
    - cd build
    - make python_sleqp_sdist
  dependencies:
    - build
  artifacts:
    paths:
      - bindings/python/dist/*.tar.gz

package_octave:
  stage: package
  only:
    - master
  script:
    - cd build
    - make sleqp_octave_package
  dependencies:
    - build
  artifacts:
    paths:
      - build/sleqp_octave*.tar.gz
