package:
  extends: .package
  dependencies:
    - build
  script:
    - cd build
    - make package
  dependencies:
    - build
  artifacts:
    paths:
      - build/*.ddeb
      - build/*.deb
      - build/*.bz2

package_wheel:
  extends: .package
  dependencies:
    - build
  script:
    - cd build
    - make sleqp_python_bdist_wheel
  dependencies:
    - build
  artifacts:
    paths:
      - bindings/python/dist/*.whl

package_sdist:
  extends: .package
  dependencies:
    - build
  script:
    - cd build
    - make sleqp_python_sdist
  dependencies:
    - build
  artifacts:
    paths:
      - bindings/python/dist/*.tar.gz

package_octave:
  extends: .package
  script:
    - cd build
    - make sleqp_octave_package
  dependencies:
    - build
  artifacts:
    paths:
      - build/sleqp_octave*.tar.gz
