.test:
  stage: test
  variables:
    CFLAGS: "-Wall"
    CXXFLAGS: "-Wall"
  before_script:
    - mkdir -p build
  dependencies: []

.test_install:
  stage: postpackage
  only:
    - master
  before_script:
    - cd build
    - apt -y install ./*.deb
    - cd $CI_PROJECT_DIR
