.test:
  stage: test
  variables:
    CFLAGS: "-Wall"
    CXXFLAGS: "-Wall"
  before_script:
    - mkdir -p build
  dependencies: []

.test_install:
  stage: postpackage
  extends:
    - .rules:default-or-release-branch
  before_script:
    - cd build
    - apt -y install ./*.deb
    - cd $CI_PROJECT_DIR

.package:
  stage: package
  extends:
    - .rules:default-or-release-branch

.release:
  stage: release
  extends:
    - .rules:release-branch
