# TODO: Run tests as soon as we can get a MUMPS version without OpenMP
test_fact_build_MUMPS:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=MUMPS -DSLEQP_LPS=$DEFAULT_LPS
    - make

test_fact_Umfpack:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=Umfpack -DSLEQP_LPS=$DEFAULT_LPS
    - make all build_tests test

test_fact_MA27:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=MA27 -DSLEQP_LPS=$DEFAULT_LPS
    - make build_tests test

test_fact_MA57:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=MA57 -DSLEQP_LPS=$DEFAULT_LPS
    - make build_tests test

test_fact_MA86:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=MA86 -DSLEQP_LPS=$DEFAULT_LPS
    - make build_tests test

test_fact_MA97:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=MA97 -DSLEQP_LPS=$DEFAULT_LPS
    - make build_tests test

test_lps_HiGHS:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=$DEFAULT_FACT -DSLEQP_LPS=HiGHS
    - make build_tests test

test_coverage:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_GENERATE_COVERAGE=On -DSLEQP_FACT=$DEFAULT_FACT -DSLEQP_LPS=$DEFAULT_LPS
    - make build_tests test_coverage

# Excluding python tests since they are built by tox
# Excluding problem scaling tests since valgrind messes with floating point exceptions
test_memcheck:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=Off -DSLEQP_FACT=$DEFAULT_FACT -DSLEQP_LPS=$DEFAULT_LPS
    - make build_tests
    - ctest -T memcheck -E "python_sleqp_tests|problem_scaling_test" --overwrite MemoryCheckCommandOptions="--leak-check=full --error-exitcode=1"

test_python:
  extends: .test
  script:
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DSLEQP_ENABLE_UNIT_TESTS=On -DSLEQP_ENABLE_PYTHON=On -DSLEQP_FACT=$DEFAULT_FACT -DSLEQP_LPS=$DEFAULT_LPS
    - make build_tests test
  artifacts:
    when: always
    reports:
      junit: ./bindings/python/python_test_output.xml
